@startgantt
projectscale quarterly
Project starts the 1st of march 2023
[Planning] as [TASK1] lasts 30 days
[Development]  as [TASK2] lasts 300 days
[Deployment]  as [TASK3] lasts 300 days
[Ongoing Support] as [TASK4] lasts 365 days
[TASK1]->[TASK2]
[TASK2]->[TASK3]
[TASK3]->[TASK4]
saturday are closed
sunday are closed
@endgantt
